SUPERKINGDOM = 'superkingdom'
PHYLUM = 'phylum'
CLASS = 'class'
ORDER = 'order'
FAMILY = 'family'
GENUS = 'genus'
SPECIES = 'species'
STRAIN = 'strain'
PHYLUM_SPECIES = [PHYLUM, CLASS, ORDER, FAMILY, GENUS, SPECIES]

UNIFRAC = 'Unifrac error'
L1NORM = 'L1 norm error'
PRECISION = 'Precision'
RECALL = 'Recall'
FP = 'False positives'
